# 4.1 NumPy

## 4.1.1 NumPyの概要
- NumPyは、Pythonで、配列や行列を効率よく使うためのパッケージ
    - ex)
        - 配列用の型であるndarrayの提供
        - 行列用の型であるmatrixの提供

## 4.1.2 NumPyでデータを扱う

### 4.1.2.1 1次元配列

In [9]:
import numpy as np

In [11]:
a = np.array([1,2,3])

In [13]:
print(a)

[1 2 3]


In [14]:
type(a)

numpy.ndarray

In [15]:
a.size

3

### 4.1.2.2 2次元配列

In [17]:
b = np.array([[1,2,3],[4,5,6]])

In [18]:
print(b)

[[1 2 3]
 [4 5 6]]


In [19]:
type(b)

numpy.ndarray

In [20]:
b.size

6

In [21]:
b[0].size

3

### 4.1.2.3 reshapeで変形

In [24]:
 c1 = np.array([0,1,2,3,4,5])

In [25]:
c1

array([0, 1, 2, 3, 4, 5])

In [26]:
c2 = c1.reshape((2,3)) # 2 x 3の行列に変換

In [27]:
c2

array([[0, 1, 2],
       [3, 4, 5]])

In [30]:
c3 = c2.ravel() # ravelで1次元に戻す
c3

array([0, 1, 2, 3, 4, 5])

### 〜だいぶ途中。その他の便利メソッドがまとめられている。